# ufunc - universal functions

In [2]:
import numpy as np

In [5]:
# square root
np_sqrt = np.sqrt([1,2,3,4,5,6,7,8,9]) 
np_sqrt

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [9]:
from numpy import pi 
print(pi)

3.141592653589793


In [12]:
# floor() towards -ve infinity

np.floor([1.1, 2.7, 3.9, 50.1, 100])

array([  1.,   2.,   3.,  50., 100.])

# shape manipulation
# flatten, resize, reshape, stack, split

In [24]:
# flatten - ravel()
new_cyclist_trials = np.array([[10,11,12,13,14,15],[16,17,18,19,20,21]])
new_cyclist_trials.ravel()

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [19]:
a = np.array([[
    [ 0, 1],
  [ 2, 3],
  [ 4, 5]],

 [[ 6, 7],
  [ 8, 9],
  [10, 11]]])
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
# reshape - changes or reshape dataset
new_cyclist_trials.reshape(3,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [32]:
# resize - resize(row,col)
new_cyclist_trials = np.array([[10,11,12,13,14,15],[16,17,18,19,20,21]])
new_cyclist_trials.resize(4,3)
new_cyclist_trials

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [36]:
# split - split the array into n
np.split(new_cyclist_trials,4)

[array([[10, 11, 12]]),
 array([[13, 14, 15]]),
 array([[16, 17, 18]]),
 array([[19, 20, 21]])]

In [43]:
# stack - merge different arrays into one array

new_cyclist_1 = np.array([1,2,3,4,5])
new_cyclist_2 = np.array([6,7,8,9,10])
np.stack((new_cyclist_1, new_cyclist_2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [46]:
# Broadcasting - Numpy uses broadcasting to carry out arithmatic operation b/w
# arrays of different shape. In this method Numpy automatically broadcast the 
# smaller array over the larger array

array_a = np.array([2, 3, 5, 8])
array_b = np.array([.3, .3, .3, .3])
scalar_c = .3

array_a * array_b
array_a * scalar_c

array([0.6, 0.9, 1.5, 2.4])

In [50]:
# Broadcasting
np_week_one = np.array([105, 135, 195, 120, 165])
np_week_one_hr = np_week_one / 15
np_week_one_hr

array([ 7.,  9., 13.,  8., 11.])

In [57]:
# Linear algebra
# Transpose - this interchange rows as column

test_score = np.array([[83,71,57,63],[54,68,81,45]])
print(test_score)

[[83 71 57 63]
 [54 68 81 45]]


In [62]:
test_score.transpose()

array([[83, 54],
       [71, 68],
       [57, 81],
       [63, 45]])

In [65]:
# linear algebra - inverse function
inverse_array = np.array([[10,20], [15,25]])
inverse_array

array([[10, 20],
       [15, 25]])

In [68]:
# inverse can only be applied on square matrix
np.linalg.inv(inverse_array)

array([[-0.5,  0.4],
       [ 0.3, -0.2]])

In [71]:
# trace() function - sum of all the elements of diagonal of a matrix 
trace_array = np.array([[10, 20], [22, 31]])
trace_array

array([[10, 20],
       [22, 31]])

In [72]:
np.trace(trace_array)

41