In [5]:
# Import numpy library
import numpy as np

In [5]:
# first numpy array
first_numpy_array = np.array([1,2,3,4])
first_numpy_array

array([1, 2, 3, 4])

In [7]:
# print first array
print(first_numpy_array)

[1 2 3 4]


In [9]:
# array with zeroes
array_with_zeroes = np.zeros((3,4))
print(array_with_zeroes)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
# array with ones
array_with_ones = np.ones((3,4))
print(array_with_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [56]:
# array with empty
array_with_empty = np.empty((3,4))
print(array_with_empty)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [58]:
# array with arange method
array_with_arange = np.arange(12)
print(array_with_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [69]:
# reshape method to change / create array
array_with_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [75]:
# linspace for evenly distributed over specified range
np_linspace = np.linspace(1,100,6)
print(np_linspace)

[  1.   20.8  40.6  60.4  80.2 100. ]


In [78]:
# print oneD array
oneD_array = np.arange(12)
print(oneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [83]:
# print twoD array
twoD_array = oneD_array.reshape(3,4)
print(twoD_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [91]:
# print threeD array
np_array = np.arange(12)
threeD_array = np_array.reshape(2,3,2)
print(threeD_array)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [86]:
# check dimension of oneD array
print('Dimension of oneD array is ', oneD_array.ndim)

Dimension of oneD array is  1


In [89]:
# check dimension of twoD array
print('Dimension of twoD array is ', twoD_array.ndim)

Dimension of twoD array is  2


In [8]:
# check dimension of threeD array
np_array = np.arange(12)
threeD_array = np_array.reshape(2,3,2)
print('Dimension of threeD array is ', threeD_array.ndim)

Dimension of threeD array is  3


# Numpy - Basic operations, based on indices

In [9]:
first_trial_cyclist = [10, 15, 17, 26]
second_trial_cyclist = [12, 11, 21, 24]

In [11]:
np_first_trial_cyclist = np.array(first_trial_cyclist)
np_second_trial_cyclist = np.array(second_trial_cyclist)

In [13]:
np_all_trial_cyclist = np_first_trial_cyclist + np_second_trial_cyclist
print(np_all_trial_cyclist)

[22 26 38 50]


In [17]:
# addition - 2 numbers
np.add(10,20)

30

In [19]:
# subtraction
np.subtract(50,300)

-250

In [20]:
# ndarray multiplication
# creates ndarray which contains number of hrs. worked for 5 days
# hourly rate is 15 usd

np_daily_wage = np.array([7,9,13,8,11]) * 15

In [21]:
# print hourly wage for each day
print(np_daily_wage)

[105 135 195 120 165]


In [22]:
# total earning after 5 days
# use sum() method to add all the data elements in ndarray

sum(np_daily_wage)

720

# Comparison Operations

In [24]:
# create ndarray for weekly hrs, 5 consecutive weeks hrs data
np_weekly_hrs = np.array([23,30,35,40,45,50])

In [26]:
# week with more than 40 hrs
np_weekly_hrs[np_weekly_hrs>40]

array([45, 50])

In [31]:
# week with not equal 40 hrs.
np_weekly_hrs[np_weekly_hrs!=40]

array([23, 30, 35, 45, 50])

# Logical Operations

In [33]:
# Logical AND operation
np.logical_and(np_weekly_hrs > 20, np_weekly_hrs < 50)

array([ True,  True,  True,  True,  True, False])

In [35]:
# logical NOT operation
np.logical_not(np_weekly_hrs > 35)

array([ True,  True,  True, False, False, False])

# Accessing Array Elements : Indexing

In [44]:
# first_trial_cyclist = [10, 15, 17, 26]
# second_trial_cyclist = [12, 11, 21, 24]
cyclist_trials = np.array([[10,15,17,26], [12,11,21,24]])

In [48]:
all_cyclist_all_trial = cyclist_trials[:]
print(all_cyclist_all_trial)

[[10 15 17 26]
 [12 11 21 24]]


In [41]:
all_cyclist_first_trial = cyclist_trials[0]
print(all_cyclist_first_trial)

[10 15 17 26]


In [49]:
all_cyclist_sencond_trail = cyclist_trials[1]
print(all_cyclist_sencond_trail)

[12 11 21 24]


In [53]:
first_cyclist_first_trial = cyclist_trials[0,0]
first_cyclist_first_trial

10

In [56]:
# : used to access all rows, then coloumn index to fetch respective cyclists
first_cyclist_all_trial = cyclist_trials[:,0]
first_cyclist_all_trial

array([10, 12])

In [57]:
# shape of the array (row, col)
cyclist_trials.shape

(2, 4)

In [58]:
# access all trails data for 2nd and 3rd cyclist from the below data matrix -
# 10, 15, 17, 26 - 1st trial data
# 12, 11, 21, 24 - 2nd trial data

In [69]:
cyclist_2_3_trial_data = cyclist_trials[:,1:3]
cyclist_2_3_trial_data

array([[15, 17],
       [11, 21]])

In [71]:
# use for loop to access all cyclist all trials
for iterate_cyclist_trials in cyclist_trials:
    print(iterate_cyclist_trials)

[10 15 17 26]
[12 11 21 24]


In [72]:
# use for loop to access - 2nd and 3rd cyclist all data
for iterate_2_3_cyclist in cyclist_2_3_trial_data:
    print(iterate_2_3_cyclist)

[15 17]
[11 21]
